import admin from 'firebase-admin'
import dotenv from 'dotenv'
import { Request } from 'firebase-functions/v2/https'

dotenv.config()
admin.initializeApp()

export interface TypedRequestBody<T> extends Request {
  body: T
}

// This part is automatically generated by Skeet Framework.
// Please do not edit this part.
// Skeet Doc: https://skeet.dev
export {
  root
} from '@/routings'
